# Generated by Django 4.1 on 2023-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.URLField(default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='topic',
            name='wide_image',
            field=models.URLField(default=None, max_length=400),
        ),
    ]
