# Generated by Django 4.1 on 2023-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_topic_image_alter_topic_wide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='topic',
            name='wide_image',
            field=models.URLField(default=None),
        ),
    ]
